# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tajinegames
# "service" is the name of this project. This will also be added to your AWS resource names.
service: meet-app-dev

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    REDIRECT_URI: https://ambrosia-fish.github.io/meet-app
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
    REDIRECT_URI: https://ambrosia-fish.github.io/meet-app


functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
          cors: true

  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
          cors: true

  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
          cors: true